name: Run CI checks
on: [ push, pull_request ]
jobs:
  test:
    steps:
      - name: Check out the repos
        uses: actions/checkout@v2
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Run linter
        run: go vet ./...
      - name: Run the tests
        run: go test ./...
