name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repos
        uses: actions/checkout@v2
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Run linter
        run: go vet ./...
      - name: Run tests
        run: go test ./...
    
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          target: app
          tag_with_ref: true
          tags: latest
